### ISSUE TITLE
Switch font hosting method

### ISSUE THREAD

**Issue by kayserifserif** [coem-lang/coem-lang.org#4]
currently using CDN Fonts, e.g. https://fonts.cdnfonts.com/css/ibm-plex-serif-2. but this uses the following syntax:

```css
@font-face{
  font-family:'ibm plex serif';
  font-style:normal;
  font-weight:400;
  src:local('IBM Plex Serif'), url(https://fonts.cdnfonts.com/s/28145/IBMPlexSerif-Regular.woff) format('woff')
}
```

i believe Firefox prevents font fingerprinting and breaks the `local` way of defining the font here? something about that combined with the way i have these font files installed (or not) and activated (or not) locally is breaking how i see the page.

this is what i see in a regular Firefox window (fonts not working):
<img width="1170" alt="Screenshot 2024-04-01 at 5 50 36 PM" src="https://github.com/coem-lang/coem-lang.org/assets/4970798/ad2f3e9f-cf5b-4fd5-bd02-9c480b78295f">

this is what i see in a private Firefox window (fonts working):
<img width="1170" alt="Screenshot 2024-04-01 at 5 50 39 PM" src="https://github.com/coem-lang/coem-lang.org/assets/4970798/122cd9a6-a425-4b85-aafd-5afd7eba41cb">
